denisvelic/UltraCompanion

- app/models/race.rb
- app/models/user.rb
- db/migrate/20221128150935_add_columns_to_users.rb
- db/migrate/20221128152950_create_races.rb
- db/migrate/20221128153731_add_user_ref_to_races.rb
- db/schema.rb
- test/models/race_test.rb
On a ajouté les models, fait les migrations
> Model setup

- .gitignore
- app/controllers/races_controller.rb
- config/routes.rb
- test/controllers/races_controller_test.rb
Pour les routes et controller à générer pour races
> Branch for project

- Gemfile
- Gemfile.lock
- app/controllers/races_controller.rb
- app/javascript/controllers/index.js
- app/javascript/controllers/map_controller.js
- app/views/layouts/application.html.erb
- app/views/races/index.html.erb
- config/initializers/geocoder.rb
J'ai ajouté le setup de geocoding, mapbox et controller stimulus plus la map sur l'index (que lon doit bouger sur la show de la course)
> geocode setup

- app/controllers/races_controller.rb
- app/javascript/controllers/map_controller.js
- app/models/race.rb
- app/views/races/index.html.erb
- app/views/races/show.html.erb
- db/seeds.rb
On a extrait les 10 premiers points d'une trace et réussi à afficher ces 10 marqueurs sur la map de la show
> add markers on map

- app/controllers/races_controller.rb
- app/javascript/controllers/map_controller.js
Ajout d'une trace entre les coordonnées sélectionnés tous les X coordonnées
> Ajout de la trace entre des points distants

- app/javascript/controllers/water_controller.js
- db/schema.rb
LES POINTS NE SONT PLUS EN AFRIQUE !!!!
> resolve points in Africa

- app/controllers/waters_controller.rb
- app/javascript/controllers/index.js
- app/javascript/controllers/map_controller.js
- app/javascript/controllers/mergemaps_controller.js
- app/views/races/show.html.erb
- app/views/waters/show.html.erb
Merge des points d'eau et du tracé sur la même map (affichage sur la show de water), besoin de customiser l'icône des points d'eau
> Merge water points and race points

- app/assets/stylesheets/components/_typo.scss
- app/views/races/new.html.erb
- app/views/races/show.html.erb
- app/views/waters/index.html.erb
- app/views/waters/show.html.erb
Préparation des liens pour le demo day
> préparation demo

- app/views/races/show.html.erb
Changement du texte de bouton de lancement de live
> modif bouton navigation

- app/javascript/controllers/map_controller.js
J'ai ajouté la fonction JS qui permet d'afficher un zoom qui prend tous les points de notre parcours
> add fitmarkers function

- app/javascript/controllers/mergemaps_controller.js
- db/schema.rb
Ajout d'une fonction JS pour géolocaliser l'utilisateur
> Add GPS location for the user

- app/assets/stylesheets/components/_card.scss
- app/controllers/races_controller.rb
- app/views/layouts/application.html.erb
- app/views/races/index.html.erb
- app/views/races/new.html.erb
- app/views/races/show.html.erb
- app/views/shared/_current_race.html.erb
- app/views/shared/_previous_race.html.erb
- app/views/waters/index.html.erb
- db/migrate/20221205133506_add_status_to_races.rb
- db/schema.rb
- db/seeds.rb
> Seeds updated

- app/javascript/controllers/mergemaps_controller.js
- app/views/shared/_current_race.html.erb
> reparation des bugs

- app/assets/stylesheets/components/_card.scss
- app/controllers/progressions_controller.rb
- app/controllers/waters_controller.rb
- app/models/progression.rb
- app/views/progressions/show.html.erb
- app/views/races/index.html.erb
- config/routes.rb
- db/migrate/20221206090547_create_progressions.rb
- db/schema.rb
- test/controllers/progression_controller_test.rb
- test/models/progression_test.rb
> page progression v1

- app/controllers/waters_controller.rb
- db/schema.rb
> debug mode

- app/controllers/races_controller.rb
- app/controllers/waters_controller.rb
- app/views/races/index.html.erb
- db/schema.rb
enfin résolu le problème import fichier gpx
> fait enfin

- app/javascript/controllers/index.js
- app/javascript/controllers/play_controller.js
- app/views/waters/show.html.erb
> setup method play pause map live

- app/controllers/progressions_controller.rb
- app/controllers/races_controller.rb
- app/models/race.rb
- app/views/races/index.html.erb
- app/views/waters/show.html.erb
- db/migrate/20221207102035_add_elevations_to_races.rb
- db/schema.rb
- db/seeds.rb
Debug elevations (migration pour ajout des elevations + seeds)
> debug mode puissance 1000

- app/controllers/waters_controller.rb
J'ai changé les points d'eau affichés (on a seulement ceux autour de Nantes)
> Change water points

- app/views/shared/_current_race.html.erb
> Apprendre à différencier l'ouest de l'est

- config/environments/production.rb
Ajout de cloudinary dans production.rb
> Ajout cloudinary

- app/views/shared/_current_race.html.erb
> Add di pour samedi

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/pages/_new_race.scss
- app/views/progressions/show.html.erb
- app/views/shared/_current_race.html.erb
Mise à jour des pages de synthèse des courses
> Mise à jour des pages de synthèse des courses

- Gemfile.lock
- app/controllers/waters_controller.rb
- app/views/shared/_current_race.html.erb
- db/seeds.rb
The method elevation gain in seed.rb retrieve the correct information.
> Elevation gain does work

- app/assets/stylesheets/components/_navbar.scss
- app/controllers/races_controller.rb
- app/views/pages/progression.html.erb
- app/views/progressions/show.html.erb
- db/seeds.rb
- db/test.rb
Elevation gain and total distance methods were updated
> races_controller was updated

- app/controllers/point_of_interest_controller.rb
- app/controllers/waters_controller.rb
- app/views/pages/point_of_interest.html.erb
- config/routes.rb
- db/test.rb
Ajout de la fonction api - point d'eau
> ajout des poi drinking waters

- db/test.rb
Upload du travail sur l'api de mapbox
> Sauvegarde du travail sur l'api de mapbox

- db/seeds.rb
Oubli de commentaire ligne 30 de seeds.rb
> commented line 30 in seeds

- db/test.rb
Ajout méthode pour parser l'api de geoapify (points d'eau)
> Add api parsing method for water markers in test.rb

- app/controllers/waters_controller.rb
- app/javascript/controllers/index.js
- app/javascript/controllers/poi_controller.js
Controlleur POI permet de venir récupérer automatiquement les POI depuis l'API de Geopify.
> Création du controlleur stimulus POI

- app/javascript/controllers/mergemaps_controller.js
- app/javascript/controllers/poi_controller.js
- Added mapbox map
- Displaying of closest drinking water points
> Solved the display of drinking water points near the user
